<a href="https://colab.research.google.com/github/arhebt3/Book-Recommendation-System/blob/main/Book_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello ")

Hello

In [ ]:
import pandas as pd

In [ ]:
!pip install keybert

Collecting keybert
  Downloading keybert-0.8.5-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.10/dist-packages (from keybert) (1.26.4)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.10/dist-packages (from keybert) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.10/dist-packages (from keybert) (1.5.2)
Requirement already satisfied: sentence-transformers>=0.3.8 in /usr/local/lib/python3.10/dist-packages (from keybert) (3.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.4.0->keybert) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.4.0->keybert) (2.18.0)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.4.0->keybert) (4.12.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2->keybert) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2->keybert) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2->keybert) (3.5.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.46.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.66.6)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.3.8->keybert) (2.5.1+cu121)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.3.8->keybert) (0.26.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.3.8->keybert) (11.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert) (2024.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert) (2.32.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert) (0.1.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2024.9.11)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.20.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert) (2024.8.30)
Downloading keybert-0.8.5-py3-none-any.whl (37 kB)
Installing collected packages: keybert
Successfully installed keybert-0.8.5

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.6)

In [ ]:
nltk.download('crubadan')

[nltk_data] Downloading package crubadan to /root/nltk_data...
[nltk_data]   Package crubadan is already up-to-date!

True

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:

# Data Manipulation
import pandas as pd
import numpy as np

# RegEx and String Manipulation
import re
import string

# Language Detection
import nltk
from nltk.classify.textcat import TextCat

# Multiprocessing
import dask.dataframe as dd
import multiprocessing

# BERT-Embeddings
from keybert import KeyBERT

# TF-IDF Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

# Plotting Heatmap of TF-IDF vectors
import matplotlib.pyplot as plt
import altair as alt
alt.renderers.enable('mimetype')

# Cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity

/usr/local/lib/python3.10/dist-packages/dask/dataframe/__init__.py:42: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

In [ ]:
# Minimum number of words that should be present in a description (value starting from 1)
min_description_word_count = 3

In [ ]:
temp=pd.read_csv("/content/book100k-200k.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/book100k-200k.csv'

In [ ]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40890 entries, 0 to 40889
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Id                     40890 non-null  int64
 1   Name                   40890 non-null  object
 2   Authors                40890 non-null  object
 3   ISBN                   40754 non-null  object
 4   Rating                 40890 non-null  float64
 5   PublishYear            40890 non-null  int64
 6   PublishMonth           40890 non-null  int64
 7   PublishDay             40890 non-null  int64
 8   Publisher              40495 non-null  object
 9   RatingDist5            40890 non-null  object
 10  RatingDist4            40890 non-null  object
 11  RatingDist3            40890 non-null  object
 12  RatingDist2            40890 non-null  object
 13  RatingDist1            40890 non-null  object
 14  RatingDistTotal        40890 non-null  object
 15  CountsOfReview         40890 non-null  int64
 16  Language               8031 non-null   object
 17  pagesNumber            40890 non-null  int64
 18  Description            35853 non-null  object
 19  Count of text reviews  40890 non-null  int64
dtypes: float64(1), int64(7), object(12)
memory usage: 6.2+ MB

In [ ]:
books_data = pd.read_csv("/content/book3000k-4000k.csv", usecols=['Id', 'Name', 'Authors', 'ISBN', 'PublishYear', 'Publisher', 'Language', 'Description'])
display(books_data.shape)
books_data.head(5)

(256595, 8)

,Id,Name,Authors,ISBN,PublishYear,Publisher,Language,Description
0,3000006,Simple Sermons on Great Christian Doctrines,W. Herschel Ford,0801091241,2001,Baker Books,NaN,A collection of simple sermons to help busy pa...
1,3000007,The Spinoza of Market Street,Isaac Bashevis Singer,0374502560,1979,"Farrar, Straus and Giroux",NaN,NaN
2,3000008,The Golem,Isaac Bashevis Singer,0374427461,1996,Farrar Straus Giroux,NaN,A clay giant miraculously brought to life by a...
3,3000009,Ujamaa Villages in Tanzania: Analysis of a Soc...,Michaela Von Freyhold,0853455120,1981,Monthly Review Press,NaN,NaN
4,3000011,Introducing Special Educational Needs: A Guide...,Philip Gardner,1853467332,2001,David Fulton Publishers,NaN,Pressure of time means that the complex topic ...

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test = train_test_split(books_data, test_size=0.6)

In [ ]:
books_data= x_train

In [ ]:
books_data.tail(10)

,Id,Name,Authors,ISBN,PublishYear,Publisher,Language,Description
222937,3629690,Operation Drvar: A Facsimile of Official Krieg...,Branislav Radovic,0764330608,2008,Schiffer Publishing,NaN,This book is a text and photographic facsimile...
70301,3189105,The Least You Should Know about English: Writi...,Paige Wilson,1413033814,2008,Cengage Learning,NaN,Quickly master English writing skills with THE...
150701,3429037,Every Day with Jesus,Greg Laurie,1565070585,1993,Harvest House Publishers,NaN,Evangelist Greg Laurie explores the intimate r...
125215,3353378,Healthy Weight Loss,Gary Smalley,0842355227,2006,Tyndale House Publishers,NaN,"Just as our relationships are interconnected, ..."
98590,3272496,Simon Starling: Nachbau/Reconstruction,Simon Starling,3865214703,2007,Steidl,NaN,"In <i>Nachbau</i>, the Turner Prize-winning ar..."
42536,3112500,Best of History Web Sites,Thomas Daccord,1555706118,2007,Neal-Schuman Publishers,NaN,This work covers over 800+ of the best history...
79437,3215528,The Text of the New Testament: Its Transmissio...,Bruce M. Metzger,0195003918,1968,"Oxford University Press, USA",NaN,This comprehensive work on the text of the New...
202074,3570756,Wisdom,Rae Desmond Jones,1875243186,1995,Blackwattle Press,NaN,NaN
216878,3612562,Ghosts Of Franklin: Tennessee's Most Haunted Town,Margie Gould Thessin,1434899829,2008,Createspace Independent Publishing Platform,NaN,"Franklin, Tennessee seriously oozes charm. At ..."
66705,3179263,Der Landschaftsgarten: Natur Und Phantasie in ...,Heidi Ebbinghaus,3631320418,1997,"Peter Lang Gmbh, Internationaler Verlag Der Wi...",NaN,Gegenstand der Arbeit ist die Diskussion des i...

In [ ]:
books_data["Id"].max() , books_data["Id"].min()

(3724836, 3000006)

In [ ]:
max_length = 50000

In [ ]:
data_books = books_data[books_data.Id.unique() < max_length ]

In [ ]:
data_books = books_data[books_data['Id'] <= max_length]

In [ ]:
data_books

Empty DataFrame
Columns: [Id, Name, Authors, ISBN, PublishYear, Publisher, Language, Description, BookSeriesInfo, Title, bow]
Index: []

In [ ]:
len(books_data.Id.unique())

183813

In [ ]:
data_books=books_data[books_data['Id'] <=50000 ]

AttributeError: 'Series' object has no attribute 'len'

In [ ]:
data_books.head()

Empty DataFrame
Columns: [Id, Name, Authors, ISBN, PublishYear, Publisher, Language, Description, BookSeriesInfo, Title, bow]
Index: []

#  Text Cleaning

In [ ]:
books_data.dropna(subset=["Description"], inplace=True)

In [ ]:
max(books_data.Id)

3724816

In [ ]:
list(books_data.Description[books_data.Id == 3724836]) #Description with url and html tag

[]

In [ ]:
url_pattern = re.compile(r'https?://\S+|www\.\S+')
def remove_url(text):
    return re.sub(url_pattern, r'', text)

html_pattern = re.compile('<[^>]*>')
def clean_html_tags(text):
    return re.sub(html_pattern, r'', text)

punctuations = string.punctuation
def remove_punctuations(text):
    return text.translate(str.maketrans('', '', punctuations))

books_data.Description = books_data.Description.apply(remove_url)
books_data.Description = books_data.Description.apply(clean_html_tags)
books_data.Description = books_data.Description.apply(remove_punctuations)

# Result
list(books_data.Description[books_data.Id == 3724836])

[]

#### Convert Letter Case to Lower and Clip Extra Spaces

In [ ]:
books_data[["Publisher"]] = books_data[["Publisher"]].fillna("unknown")
books_data[["Name", "Authors", "Publisher", "Description"]] = pd.concat([books_data[col].astype(str).str.lower().str.strip()
                                                                             for col in ["Name", "Authors", "Publisher", "Description"]],
                                                                            axis=1)

In [ ]:
books_data.head(10)

,Id,Name,Authors,ISBN,PublishYear,Publisher,Language,Description
67726,3182244,spring moon,bette bao lord,0380599236,1982,avon books,NaN,in a world gone forever at a time of mystery a...
206334,3582484,the chaos weapon,colin kapp,0345313445,1983,del rey,NaN,classic scifi novel based around the attempt t...
254061,3717691,homeless across america,kevin e. lake,0595503977,2008,iuniverse,NaN,homeless across america is the story of a man ...
102594,3283932,toltec mounds and plum bayou culture: mound d ...,martha ann rolingson,1563490854,1998,arkansas archeological survey,NaN,excavations of mound d serve as a springboard ...
19897,3050942,"the art of white: painting, photography, illus...",edwin bowes,1902970306,2005,lowry press,NaN,the art of white at the lowry is an exhibition...
119892,3337351,norman rockwell: the artist and his work : the...,norman rockwell,1567997600,1999,metrobooks (ny),NaN,for seven decades norman rockwell captured the...
106766,3296005,gliding,derek piggott,0389207489,1988,rowman & littlefield publishers,NaN,an illustrated volume on gliding it includes a...
87398,3238829,tba -- les jumeaux bulle series,bertrand gauthier,2890216845,2004,la courte echelle,NaN,the premier roman series was especially design...
131985,3374261,post-fandom and the millennial blues: the tran...,steve redhead,0415115272,1997,routledge,NaN,soccer fandom has traditionally been seen as a...
41193,3108490,please let it snow! (i'm going to read® level 2),barry gott,1402730896,2006,sterling pub co inc (j),NaN,new boots new jacket new hat…but no snow kids ...

## Remove Book Descriptions With Shorter Length.

In [ ]:
# Find description word count
books_data["length"] = [len(d.split()) for d in books_data['Description'].tolist()]

print(set(books_data.Description[books_data.length.isin(range(0,4))]))

{'', 'わたしは……だれ？記憶を失った少女・パセリの心の旅が、今、始まる！事故で両親と“記憶”をなくした11歳の少女パセリは、北海道で牧場を営む祖父母のもとで暮らしはじめる。パセリが心を許せるのは新しい学校の同級生で親友になったレンゲだけ。記憶を取り戻したいパセリは、森でであった少年隼人の協力で自分の過去について調べるうち、祖父母の意外な秘密を知ってしまう。やがて浮かびあがるさまざまな謎。そんなとき、レンゲとの友情をゆるがす事件が。', '今度はなんと銭湯の湯船から異世界へと流されたユーリ。美形で有能な臣下たちと共に、永らく行方不明になっていた「魔剣モルギフ」を探す旅に出たが……。ｔｖアニメ「今日からマ王！」の原作第２弾、《魔剣編》登場', 'farmersagricultural policymakersenvironmentalists', '同級生のユキから突然告白されてしまった天鳥あとり。初めてユキを性的に意識した天鳥は、ついに流されるままsexの直前までいってしまう嫌悪を感じない自分も、やはりゲイなのか──。悩む天鳥は答えを求めるように、美貌の男娼・トオルと一夜を共にして…\u3000単行本未収録amp一挙描き下ろし115pで贈る、待望の第2巻', '江戸に上京して以来音信不通の息子・八郎を捜しに来た母親を手伝うことになった万事屋一行。だが八郎はヤクザ絡みのトラブルに…！？\u3000他にも桂密着ドキュメントとか団子大食い大会とか…。そしてなんとお妙に許嫁が！？', '穏やかな陽射しが落ちる秋の一日、ボストン午後3時3分。世界は地獄へと姿を変えた。《パルス》。そのとき携帯電話を使用していたすべての人々が、一瞬にして怪物へと変貌したのだ。残虐極まる行為もいとわず、犠牲を求め続ける凶悪な存在に――。目前で突然繰り広げられる惨劇、街中に溢れる恐怖。クレイは茫然としていた。いったい何が 別居中の妻と息子は 巨匠の会心作、開幕', 'poetry textbook', '舞台は沖縄、何かに感謝したくなる、四つの物語。', 'western', '辺境の輸送隊の護衛役を引き受けたｄは、犠牲者の娘を伴い、史上最凶の貴族として恐れられていたギャスケル将軍の領地へと向かう。', '4 audiocassettes', '「草枕」「雁」「羅生門」などの新しい解読のなかから文学テクストが約束する〈読書のユートピア〉へと読者を誘う。文学研究に新領域を切り開いた著者の最後の仕事。', 'novel in spanish', 'biographies', 'gt', '《人行道的尽头》谢尔·希尔弗斯坦作品集06是作者的第一本诗集绘本，1974年一经出版便立刻被奉为经典。这些诗与画体现出的幽默、智慧、温情使人击掌喝彩。想象力在本书中是最不缺乏的部分：因为被污染的世界而不愿意被蛋生出来的小鸡，为什么独角兽不存在了，一份河马三明治食谱；或是一些孩子最简单的愿望：低价拍卖爱哭的小妹妹，可以擦掉讨厌鬼的神奇橡皮擦，害怕黑暗得在床边开盏灯……任何孩子想得到，大人已经遗忘的，都可以在这本书里找到。简体', 'html', 'facsimile edition', 'on hindu astrology', '20 maps', 'ホロの故郷・ヨイツを目指し、二人の旅は続く……。狼神ホロの故郷・ヨイツを探すため、北を目指す行商人のロレンス。異教徒の町・クメルスンで得た情報をもとに、二人は田舎の村・テレオにやってくる。テレオの教会にいる司祭は、異教の神々の話を専門に集める修道士の居場所を知っているという。しかし、教会を訪れたロレンスとホロを出迎えたのは、無愛想な少女・エルサだけだった。さらにテレオでロレンスたちは、村存続の危機に巻き込まれてしまう。はたして二人はヨイツへの手がかりをつかみ、無事に村を出立できるのか……。', '背筋が凍る恐怖からもう、逃げられない！！華やかなヴィクトリア朝ロンドンの街\u3000猟奇的連続殺人のそのわけは？猟奇的な連続殺人犯「切り裂きジャック」。残忍な犯行はロンドンばかりでなく、郊外やフランスにも及んでいたのか！？コーンウェルが推理作家ならではの大胆な推理と、スカーペッタさながらの冷静で細心の調査にもとづいて、真犯人を追い詰めていく。すさまじい情熱を傾けた、著者渾身のノンフィクション。', 'country inspired rooms', '抱腹絶倒ファンタジー、只今参上ヤンキーに絡まれたメガネくんを助けて、返り討ちにあった渋谷有利・15歳。トイレに連れ込まれた末に便器に顔をと思ったらナゼかいきなり異世界に。おまけに俺が魔王って 大人気小説がついにコミック化', '歴史の裏を知り尽くした著者が、西洋名画に秘められた恐るべき怨念・冷酷・非情をとき明かす、知的でスリリングな美術エッセイ、大好評につき第二弾まだまだあった、ますます鮮やかな名画の謎解き、今回は、◎フォンテーヌブロー派の逸名画家『ガブリエル・デストレとその妹』……なぞめいて扇情的な「浴槽の美女」、彼女の死後に描かれたとしたら◎ルーベンス『パリスの審判』……のどかな神々の美人コンテスト、欲情と見栄が生んだ悲劇とは◎ピカソ『泣く女』……女性を見つめるピカソの眼、どうしてこんなに怖いのか他、ベラスケス『ラス・メニーナス』、エッシャー『相対性』など、20作品豪華カラー図版掲載。「絵ってすごい」「こういう切り口の絵の本はなかった」と各メディアで絶賛\u3000本書を読めば、絵画の見方が拡がります。', 'シリーズ第3弾！ ロレンス…… わっちは、ぬしのなんじゃ？行商人のロレンスと狼神ホロが、冬の大市と祭りで賑わう町クメルスンへと着くと、若い魚商人・アマーティがホロに急接近してきた！ロレンスとホロの間に微妙な気持ちのすれ違いが生じ、あらぬ誤解が……。ロレンスとアマーティそれぞれの商売をも巻き込んだ大騒動が始まる！', '落ち目の舞台俳優・トビーは地方巡業先で、離婚訴訟中の妻から助けを求められた。自室が見張られているというのだ。まだ未練が残る妻の身辺を探るうちにトビーが掴んだのは、多くの人命を犠牲にして繁栄した資産家一族の暗部だった。ストーリーテラーの本領発揮巨匠が放つ最もスピーディーなサスペンス。', '灰谷健次郎のライフワーク待望の文庫化！あの倫太郎が中学生になった。不登校、暴力・・・、厳しい子供のいまをじっくりかつ朗らかに描き出す必読の小説。', '新術発動ッ！！\u3000四代目火影でさえ、成し得なかったナルトの風遁・螺旋手裏剣が角都を打ち砕く…！\u3000一方、大蛇丸を襲うサスケ。生死をかけた師弟の戦いは非情さを増し…。果たしてサスケの中に残るのは――！？', '武島直貴の兄・剛志は、弟を大学に入れてやりたいという一心から、盗みに入った屋敷で、思いもかけず人を殺めてしまう。判決は、懲役15年。それ以来、直貴のもとへ月に1度、獄中から手紙を送る剛志。一方で、進学、恋人、就職と、つかもうとした人生の幸福すべてが「強盗殺人犯の弟」というレッテルによって、その手をすり抜けていく直貴。日を追うごとに、剛志からの手紙は無視され、捨てられ、やがて…。', 'guillermo roux art', '内容紹介「nhkにようこそ」の滝本竜彦が贈る、前人未踏の妄想小説ひきこもり新人作家は気づいた。辛い現実を前に立ちすくみ、ダメ人間ロードを突き進む自分を変えるには「超人」になるしかないのだと――女神のごとく降臨した脳内彼女レイちゃんと共に、進め超人への道内容（「book」データベースより）新人作家は悩んでいた。厳しすぎる現実を前に立ちすくみ、ダメ人間ロードを一直線に突っ走る自分はこのままでよいのだろうか…いや、よくない虚無感とルサンチマンに支配された己を変えるには、そうだ“超人”になるしかないのだ「くじけてはダメ、ゼッタイ」やさしく励ます脳内彼女レイと手を取り進め、超人への道『nhkにようこそ』の滝本竜彦が現実と虚構のはざまに放つ前人未踏の超絶ストーリー。', '17 maps', '《沉香》收录张爱玲以往未曾正式结集出版的散文、电影剧作（包括《不了情》、《太太万岁》、《一曲难忘》、《伊凡生命中的一天》）、亲笔插画和个人遗物的照片。封面装帧极具张爱玲味——封面亮丽的桃红色，参照了张爱玲旗袍面料花瓣的颜色；书中环扉的古蓝色，参照的是张爱玲披肩的颜色；彩插的米黄底色，则是张爱玲毛衣的主色。书中许多细节都是在专家的悉心考证下最后确认的。比如剧本《一曲难忘》是香港科技大学郑树森教授根据油印本整理而成，因为原稿的模糊，也留下了些许存疑文字。张爱玲根据俄罗斯作家索尔仁尼琴《伊凡生命中的一天》改编的广播剧本，则是翻译家乔志高的悉心保存。《不了情》这个连张爱玲自己都痛惜已经散佚的电影，被编者陈子善教授在vcd中发现。可以说，是众多学人披沙拣金般的努力促成了《沉香》的出版幸事。在文集的篇目选择上，还特别收入一本张爱玲的伪书《笑声泪痕》的书影。《沉香》还首次收入了张爱玲生前私人物品的照片。张爱玲过世后，这些物品由遗嘱执行人林式同运至香港交给张爱玲遗产的继承人宋淇夫妇，经宋淇夫妇整理后，再转交台湾皇冠出版公司保存。其中有服饰、鞋子、眼镜、手表、笔、化妆品等。张爱玲的鞋子数量很多，并且都很精致；手表被精心收藏在首饰盒中的暗格里，这些都不同程度地展示出张爱玲的日常生活。', '本书介绍了越南南部阮氏王朝的新领土内区武装力量外国客商货币与贸易阮氏税收制度以及越南人与高原人等内容。', 'german library', '前途一片黑暗，沒有出口。這樣的人生該持續下去嗎？在經濟蕭條壓力下苦求生存的鐵工廠老闆川谷，同時面臨附近居民抗議、以及與銀行貸款的糾紛。任職於銀行的小綠由於家庭問題與職場性騷擾的問題，每天都過得非常憂鬱。靠著打小鋼珠和恐嚇他人過活的和也，因為受到流氓威脅，走投無路的他只好鋌而走險．．．小工廠老闆、銀行女職員與小混混，當原本毫無交集的三個人在人生的岔路上相遇時，命運開始失速下降，墜入最糟糕的結局．．．走投無路的人們，如何戲劇性地捲入一場震驚社會的銀行搶案？', '紫式部の「源氏物語」をもとにした、ドラマチックな平安王朝ストーリーの第2巻光源氏は山寺でひとりの少女と出逢う。少女はなぜか、初恋の人、藤壺の宮にそっくりだった。藤壺の宮をわすれることができない源氏は、ある日――。一方、正妻の葵の上とは少しずつ心が通いはじめていた。しあわせをつかみかけたそのとき、ふたたび悲劇が訪れる……真実の恋は手にはいるのか運命の車輪が、まわりはじめる――。紫式部の「源氏物語」をもとにした、ドラマチックな平安王朝ストーリーの第2巻光源氏は山寺でひとりの少女と出逢う。少女はなぜか、初恋の人、藤壺の宮にそっくりだった。藤壺の宮をわすれることができない源氏は、ある日――。一方、正妻の葵の上とは少しずつ心が通いはじめていた。しあわせをつかみかけたそのとき、ふたたび悲劇が訪れる……', '這是村上春樹一九九○年秋天開始至一九九三年之間，在普林斯頓大學任教時寫的隨筆散文。有別於旅遊歐洲時《遠方的鼓聲》的旅行書寫，這是村上實際「歸屬」於美國這個社會，在這裡生活的觀察紀錄，以照片來說，是他「從普通的距離，拍攝極其平常的東西」。他寫了當時正在發生的波灣戰爭、拜訪費滋潔羅的孫女的點滴、在美國跑步與在日本跑步有何不同、美國大學的階級制度等等。筆調有村上一貫的輕鬆幽默，比如〈禁止攜帶酸梅乾飯盒入場〉一文中，這句話要說的其實是美國的反日浪潮。然而，雖然是生活在美國，村上春樹終於是個stranger，是個外國人，因此，他總覺得有一種深深的悲哀，被一種「不是不用學就自然明白的語言」團團圍住，這種狀況就包含著悲哀的東西。這也就是書名《終於悲哀的外國語》的由來。', '水族館のイルカプールから、またまた異世界へと流されたユーリ。吹けば嵐を呼ぶという魔族の秘宝「魔笛」を探しに、人間たちの国へと向かうハメに……。ｔｖアニメ「今日からマ王！」の原作第３弾、《魔笛編》参上！', 'ハルヒと出会ってから俺はすっかり忘れた言葉だが、あいつの辞書にはいまだに”退屈”という文字が光り輝いているようだ。その証拠に俺たちsos団はハルヒの号令のもと、草野球チームを結成し、七夕祭りに一喜一憂、失踪者の捜索に熱中したかと思えば、わざわざ孤島に出向いて殺人事件に巻き込まれてみたりして。まったく、どれだけ暴れればアイツの気が済むのか想像したくもないね…。非日常系学園ストーリー、天下御免の第３巻！！', 'jan morris introduction', '《呼蘭河傳》是民國才女蕭紅在香港創作的一部長篇小説，也是她的巔峰之作。小說以作者的家鄉和童年生活為原型，描繪出了作者記憶中的家鄉呼蘭——上世紀二、三十年代一個東北小鎮的單調與美麗、人民的善良與愚昧。全書七章：一、二章寫小城風情，三、四章談家中親疏人物，五、六、七章摹繪獨立旁枝人物。七章可各自獨立又渾然一體。', 'oeuvre de dante', '「問題在……她對很多事情都不太容易適應。不管是自己的身體、自己所追求的東西、或別人所要求的東西……」村上春樹村上春樹在無聊又無奈的現實生活中的異想天開，反映了現在都市人孤獨的影子。', '警察がでっちあげた証人とお粗末な科学捜査により、ロンは死刑判決を下される。12年にもわたる過酷な刑務所暮しがはじまった。刻一刻と迫りくる死刑執行の期日。徐々に彼は精神を蝕まれていったが、そこにdna鑑定という一筋の光明が差し込む…。綿密な取材で捜査当局の不正義を容赦なく白日の下にさらした、全米ベストセラー。', '這本書收錄了村上最新創作的五部短篇小說，是《神的孩子都會跳舞》之後的最新短篇。以都市奇譚的面貌、將人生體悟與怪誕故事交織，較之之前的短篇小說，村上創作25年的說故事能力越來越讓人嘆為觀止，除了上市後在日本登上暢銷書榜首，更引起美國的注目，紐約客和哈潑雜誌都即時就翻成英文以饗英語讀者。特別薦給喜歡早期聽風的歌、彈珠玩具，35歲以上，結婚超過五年，不論有無小孩的村上讀者。', '服作りに情熱を燃やす“ヤザガク”の４人と出会ってしまった受験生、紫。リーダーのジョージに振り回されつつ、彼らのドレス作りに参加するが成績は下がり始め…。10言語で翻訳、全世界で愛読されている恋とミシンとステージの青春ストーリー！', 'ph 306', '87th precinct novel', 'temples of sovereignty', '森羅天頂武闘大会・zott第1回戦、ガリィは敵副将クー・ツァンと激突 戦うことの真の意味を見い出したガリィには、恐れも戸惑いもなかった。しかし、敵大将のカエルラ・サングウィスと対峙したとき、ガリィの身の内を忌わしい恐怖の記憶が駆け抜ける 忘却の彼方に浮かんでは消えるガリィの記憶と、深い謎に封印されたカエルラの過去……。ふたりが再び遭いまみえたことで、運命の歯車は静かに回り始めていた。宿命さえも捩じ伏せる、熱きオーラがほとばしるsfハイパー・バトル第6巻', 'lessons on aesthetics', 'ついに一行はクラウハウゼンの村に入った。dは男爵を守り抜き、契約は果たされたのだった。dと別れた男爵は、最後のそして最大の仕事をやり遂げるべく、己れの呪われた過去が秘められた父ヴラドの居城へと向かった。だがそこには、奇怪な老科学者カリオールに率いられた三人の刺客が待ち受けている。ヴラドの魔手は同時にdにも伸び、辺境の村で凄惨な戦いがはじまろうとしていた。', 'null', 'no', '口ひげの小男トム、十五歳の少女アリスが仲間に加わった。クレイは彼らとともに最愛の息子の無事を祈りながら「我が家」のあるメイン州を目指す。だがその一方で携帯狂人は群れを形成するようになり、振る舞いも進化していく。そして、リーダーらしき人物の登場……。絶望的なまでに人無き荒野をゆく三人の旅のゆくえと、彼らを襲う悲劇とは。人類の未来をも問う、心揺さぶる結末。', '《兜售回憶》有回憶要兜售嗎？歡迎來臨這小店，擬一個好價錢，寄賣你的回憶。我能出售相愛的回憶，但要忘了你，卻談何容易……想出售回憶嗎？在『memories』，愈真誠的回憶愈值錢……因車禍失去記憶的初二開了這家小店，沒想到生意出奇地好。兜售回憶，或為忘卻痛苦的過去，或為分享幸福，更有人寄售信物只求與情人重遇……原來，相愛的痕跡會填滿原本沒有生命的各樣玩意。但身處眾人的故事之中，初二還是怎麼也等不到自己的回憶，直到有一天，神秘的粉綠色信件拆穿了所有謊言，初二遺忘的，難道是最珍貴的……', 'in three volumes', 'やり手の広告代理店プランナーが、仕事上で屈辱を味わわされた大手自動車メーカー副社長への復讐を思いつく。仕事も恋愛も人生はすべてゲーム、それに勝ち抜くことがすべてと信じるエリートのプライドが、物語の重要な背景となっている。そこに家出中の副社長の娘が絡み、ラブストーリー的な要素も加わっていく。おのおのの思惑が思わぬ方向に事態を変化させていくあたりは、稀代のストーリーテラーとしての著者の面目躍如だ。', '内容紹介新世代青春小説の金字塔「雪崎絵理は戦う女の子だ。美少女戦士なのだ」。目的を失った日々を”不死身のチェーンソー男”との戦いに消費してゆくセーラー服の美少女絵理と高校生山本の切ない青春。青春小説の新たな金字塔。内容（「book」データベースより）「ごめんなさい。やっぱり私はあいつと戦います」平凡な高校生・山本陽介の前に現れたセーラー服の美少女・雪崎絵理。彼女が夜な夜な戦うのは、チェーンソーを振り回す不死身の男。何のために戦っているのかわからない。が、とにかく奴を倒さなければ世界に希望はない。目的のない青春の日々を“チェーンソー男”との戦いに消費していく陽介と絵理。日常と非日常の狭間の中、次第に距離が近づきつつあった二人に迫る、別れ、そして最終決戦。次世代文学の旗手・滝本竜彦のデビュー作、待望の文庫化。', '巨額の遺産を相続した若い独身女性の家に侵入してみると、なぜかどの部屋のなかも鏡だらけ。意外な結末が待ち受ける「ステップファザー・ステップ」など、すばらしい着想と軽妙なユーモアに彩られた傑作7編', '很多人認為，舊約聖經似一本封閉的書。他們覺得舊約的世界及文化跟他們很遙遠，內容又繁雜，不易找到明確的思想主線，故此知難而不敢去讀。本書作者是卓越的舊約學者，曾任多間著名學府的講師。他在書中對舊約聖經作了簡明的引介，使讀者瀏覽不多的篇幅，就可全面了解舊約聖經的中心教訓，是理解舊約聖經的入門好書。', 'ついに黒い（ノアール）プリンセスになってしまったバニラ。胸の苦しみをこらえ、黒い（ノアール）ハートを集めるバニラと、そんな彼女を救いたいと思いながらも、ピエールへの思いを断ち切れないショコラ。2人の女王（クイーン）候補試験のゆくえは……！？', '「光にメロディがあるの」「あるさ。みんな、そのことに気づいていないだけさ」。“光”を“演奏”することでメッセージを発信する天才高校生・光瑠。彼の「光楽」に、感応し集う若者たち。しかし、その力の大きさを知った大人たちの魔の手が忍び寄る。', '「祇園精舎の鐘の声，諸行無常の響きあり」－『平家物語』が都の辻々で語られた中世鎌倉時代は，全国各地で新興武士勢力が割拠する一方で，新しい創造性に満ちた仏教が民衆の広い支持を集めた時代だった．本書では源平の争乱から鎌倉幕府成立，蒙古襲来を経て，室町時代の御所で華麗な能楽が舞われた応仁の乱前夜までを活写する．', '親友のバニラに後れをとりながらも、ショコラは魔界の女王（クイーン）を目指し、人間界で修業中。一方、妖しい魅力の美少年・ピエールが、何の企みか、ショコラに近づいてきて……。大人気マジカル・ラブ・ファンタジー第2弾！', 'なぜ、もっと早くに出会わなかったのだろう――携帯サイトで知り合った女性を殺害した一人の男。再び彼は別の女性と共に逃避行に及ぶ。二人は互いの姿に何を見たのか 残された家族や友人たちの思い、そして、揺れ動く二人の純愛劇。一つの事件の背景にある、様々な関係者たちの感情を静謐な筆致で描いた渾身の傑作長編。', 'いよいよ、森羅天頂武闘大会・通称zottが始まった。ルウ奪還の望みを賭け、ガリィはゼクス、ピングらとともに、トーナメントに挑むことになった。しかし、ガリィの心の深淵には死と恐怖の亡霊が巣食い、多くの犠牲を生み出す闘いの意味を掴めずにいた。闘いたくない、でも…… 立ちはだかる強敵を前に、戸惑い怯えるガリィは、真の戦士として覚醒できるのか 白熱のsfハイパー・バトル第5巻', '1887', '何かしなければ、何も変わらない。灰谷健次郎ライフワーク文庫化！倫太郎が通う中学校で４名の少年が検挙された。校舎の窓ガラスを割った疑いらしい。きちんとした対応をとれない学校に対し、教師への違和感は爆発する。そんな中、倫太郎たち、教師、あんちゃんらが一堂に会する。', '全項目を再検討し、新たに1万項目を収録。総収録項目数は24万を超える。新しい意味や用法の広がりを的確に捉え、現代の急速な社会の変動やさまざまな分野での研究の進展、科学技術の進歩に伴って生じた新しい動きを反映。「漢字・難読語一覧」「アルファベット略語」などの別冊付録も充実。印刷・造本上の新工夫も随所に。50年余にわたって読者の信頼を得てきた『広辞苑』、10年ぶりの最新版。', 'brown ann mariedescripallowedextsubjallowed', '電車内で暴れる酔っ払いから若い女性を救った、ヲタク青年。女性に縁がない彼は、彼女をデートに誘うべく、モテない男たちが集うインターネットサイトに助けを求める。いつしか「電車男」と呼ばれるようになった彼に、出来る限りのアドヴァイスを与え、時に叱りながらも温かく見守る仲間たち。熱い励ましは「電車男」に勇気を与え、彼女との距離を一歩一歩縮めていく。「電車男」は果たして意中の彼女に告白できるのか読む人全てを熱い共感の渦に巻き込む、リアル・ラブ・ストーリー。', 'hardbound', 'glycolipids', '男の極楽、女の地獄。ここは遊廓、江戸吉原。', 'guidebook on india', 'x', '鮭とごぼうの炊き込みごはん、いわしの梅煮、たけのことがんもとこんにゃくの煮物、栗ごはん、トマトとツナのぶっかけそうめん、鶏肉のオーブン焼き、ナスとトマトと豚肉のピリ辛中華風煮込み、いちごジャムetc……', 'おりしもヴァチカンは次期教皇選挙の日。ところが有力候補四人が失踪してしまった……次々起こる見立て殺人。ラングドンは知力の限りを尽くして姿亡き敵を追う！とてつもないスケールで描く驚天動地のラスト！', 'くもの糸大どろぼうの犍陀多かんだたは、死後地獄で苦しんでいた。お釈迦様は、昔犍陀多がくもを助けたのを思い出し、極楽からくもの糸をたらした。それにすがって、犍陀多は極楽をめざしてのぼっていくが……杜子春仙人のおしえで、2度まで一夜にして都でいちばんの大金持ちになった杜子春とししゅんは、世の中のむなしさから、仙人になろうとするか 芥川龍之介の名作11編を収録収録作品・クモの糸・杜子春・魔術・たばこと悪魔・白・雛・トロッコ・龍・鼻・3つの宝', 'a sociological perspective', '本書は、perlをより深く知りそして活用するためのアイデアと、perlによる実践的なプログラミングテクニックをふんだんに盛り込んだレシピ集です（全２冊）。volume 1には、perlの基本データ型、パターンマッチ、ファイルシステムなど基本的な処理のほか、プログラムをフレキシブルで強力にするために欠かせないリファレンス、モジュール、オブジェクトなどに関するレシピを収録。volume 2には、データベースアクセスやユーザインタフェース、ネットワークプログラミング、インターネットサービス、webアプリケーション関連のレシピを収録。また、modperlとxmlに関する章を新しく設けています。perlプログラマが直面するプログミングの課題を幅広く取りあげ、そのすべてに実践的な解法を示しています。すべてのperlプログラマへ本書を捧げます。', '（玉宇呈祥）是長篇小說（康熙大帝）系列的第三卷。擒服熬拜，平息「三藩」之亂以後，康熙視察黃河，四處物色治河能臣，疏通漕運；任用良將，東收台灣；開博學鴻儒科，緩和漢滿民族矛盾；南巡金陵，祭祀明太祖，團結前明遺老；整頓吏治，懲辦貪官；北巡盛京，與東蒙古諸王結盟；西征葛爾丹，完成統一大業。（玉宇呈祥）一書，描寫了康熙在錯綜複雜的情勢之中，以高超的統御能力，領導國家走向中國歷史上少有的承平盛世。另一方面，作者也描寫了康熙和朝臣之間關係的變化。步入中年的康熙，雖不失仁慈，但心機卻更加深沉，猜疑心日重。原來忠心不貳的功臣，逐漸腐化，互相結黨攻訐。作者深刻的闡述了「盛世之中有隱憂」的這一主題。', '◆日本龍皇杯小說比賽冠軍！◆改編成漫畫、動畫、遊戲，風靡全日本的no1輕小說！◆內附典藏折口書籤！武雷神大暴走？！千萬別靠近沒睡醒的拉蔻兒，小心她會濫用恐怖魔法喔～～「堅強的人也有軟弱的時候，猶豫的時候，想要被救贖的時候，想聽別人說『你沒問題』的時候。」帕希菲卡，十五歲，假如閉上嘴巴，也算是個美少女。然而，其實她就是神諭宣告會在十六歲時毀滅世界的「廢棄公主」。為了保護她不被刺客殺害，卡蘇魯三兄妹今天也繼續永無止盡的旅行。這回他們遇見一個自稱貝爾肯斯的瑪烏傑魯教異教檢察官，貝爾肯斯跟帕希菲卡因為雞蛋料理而一拍即合！可是，他是為了追殺廢棄公主才來這裡的，而且很快地他們大家就碰上了率領著一群異教徒的「廢棄公主」……。人人追殺的「廢棄公主」為什麼會有人想假冒呢？一個人面具戴久了，面具可能會變成真正的臉孔喔！請傾聽被迫害的異教徒交織出的死亡安魂曲……。', '如果身心做不了主，受環境影響，結果反映出來的都是環境，不但失去了自己，也失去了真正的面目。本書是用一百則禪語的解說，代替教授禪修方法，讓讀者們從禪語的解說中體驗禪修者的心境；遇到困頓逆境時，可以當作避風港；遇到煩惱痛苦時，可以當作清涼散；遇到奈無聊時，可以當作緩和衝撞的手剎車。', '検屍官シリーズ驚愕の新展開で今年も登場！\u3000フロリダに落ち着いたスカーペッタに古巣バージニア州検屍局からの依頼が届いた。自宅で独り変死した少女は病死か他殺か。わずかな痕跡が新たな事件の幕を開く！', '美しい幻想の物語「紅い花」をふくむ、13篇の「つげ義春の世界」▼第１話／紅い花▼第２話／李さん一家▼第３話／通夜▼第４話／海辺の叙景▼第５話／西部田村殺人事件▼第６話／二岐渓谷▼第７話／ほんやら洞のべんさん▼第８話／女忍▼第９話／古本と少女▼第10話／もっきり屋の少女▼第11話／やなぎや主人▼第12話／庶民御宿▼第13話／近所の景色●少女がたった１人で番を務める峠の茶屋がある。ある日、釣にやってきた男がそこに立ち寄った。彼がしばらく休んでいると、そこに少女の同級生のマサジがやってくる。マサジに案内されて、男はヤマメの穴場へと向かうが、その道中で彼は見知らぬ紅い花が群生しているのを見る。そうこうしているうちに彼らは穴場に到着し、男と別れたマサジは山道を戻ってゆく。そのときふとマサジは、茶屋の少女が川の浅瀬に入ってしゃがみ込む姿を目撃する。マサジの目の前で、少女の臀部から出る鮮血の流れが、落ちてくるたくさんの紅い花を飲み込んで流れてゆく…（第１話）。●日光浴をする男の脇に、美女が寝転がる。彼はその女性に好意を抱くが、声をかけることもできず、連れらしき男に嫉妬するばかり。ところが、日が暮れた海に男が再びやって来ると、そこにはたった１人で彼女が膝を抱えていた。昼間の男について彼が尋ねると、その男は彼女の連れではなく、宿で知り合っただけだという。これをしおに、彼らは大した意味もないことを淡々と話し続け、再会を約束して別れる。その翌日、雨が降りしきる中を待ち続ける彼のもとに、息せききって彼女が走ってきた。彼女は彼に、翌日東京へ戻ることを打ち明け、泳ぎ納めと言って海に入ってゆき、彼もそれに付き合って泳ぎ始める。彼女に泳ぎを褒められ、彼はいつまでもいつまでも泳ぎ続ける（第４話）。', 'two volumes', '1939 translation', '今年のバレンタインデーこそ、つかさから直接チョコレートをもらいたい…！！\u3000綾たちからチョコレートをもらいながら、贅沢な願いを持つ淳平。待ち続けてようやく訪れた至福の時、つかさから衝撃的な発言が出て…！？', 'textformat02gt', '破天荒な行動力と自由闊達な心を持つ少年、倫太郎の成長を通して、学ぶこと、生きること、自由であることのすばらしさを描く、灰谷文学の集大成。生きることを問うライフワーク。', 'bilder und geschichten', 'ab 11 j', 'in two volumes', 'graphic presentations sidebars', '新学期を迎え、身体検査の日が近づいて来た。しかしハルヒが女の子であるとバレて、ホスト部にいられなくなってしまうのはマズイ そこでホスト部の総力をあげた「ハルちゃんは断じて男の子」作戦が発動され…\u3000短編『ロマンティック・エゴイスト』も併録。', '莎拉為了救罹患急性前骨髓性白血病的女兒凱特，利用醫學科技生下與凱特有完美基因配型的安娜。十三年來，安娜不斷地供應凱特血液、白血球、骨髓、幹細胞，現在輪到了她的腎臟。無法忍受再被當成藥糧的安娜決定反擊她的父母，控告父母奪走她的身體使用權。《紐約時報》暢銷作家皮考特以不同人物的口吻來接續故事的發展，探討一個極具爭議性的話題；對「愛」有深入的刻劃及詮釋，以細膩的筆法，精妙的細節，靈巧的掌握人與人之間脆弱敏感又錯綜複雜的關係。', 'ampltbr ampgt ampgt', '私はたぶん泣きだすべきだったのだ。身も心もみちたりていた恋が終わり、淋しさのあまりねじ切れてしまいそうだったのだから――。濃密な恋がそこなわれていく悲しみを描く表題作のほか、17歳のほろ苦い初デートの思い出を綴った「じゃこじゃこのビスケット」など全12篇。号泣するほどの悲しみが不意におとずれても、きっと大丈夫、切り抜けられる……。そう囁いてくれる直木賞受賞短篇集。', '娘の緑子を連れて豊胸手術のために大阪から上京してきた姉の巻子を迎えるわたし。その三日間に痛快に展開される身体と言葉の交錯', '首なし死体、密室、蘇る死者、見立て殺人……。京都近郊に建つヨーロッパ中世の古城と見粉うばかりの館・蒼鴉城を「私」が訪れた時、惨劇はすでに始まっていた。2人の名探偵の火花散る対決の行方は。そして迎える壮絶な結末。島田荘司、綾辻行人、法月綸太郎、三氏の圧倒的賛辞を受けた著者のデビュー作。', '仇敵を討つ！\u3000修業に励むナルトに届くアスマの訃報。悲しみに暮れる間もなく、第十班はカカシと共に再び木ノ葉へ潜入する“暁”と対峙する。シカマルの作戦で優位に戦いを進める中、角都の驚愕の能力が明らかに！！', 'rudyard kipling 1865', '雨の日、だるまちゃんが外に遊びにいくと、空から浮き輪とかみなりちゃんが落ちてきました。だるまちゃんは、木に引っかかった浮き輪を取ってあげようと、傘を投げますが、傘もいっしょに引っかかり、二人で困ってしまいました。そこに雲に乗った大きなかみなりどんが迎えにきて、お礼にだるまちゃんをかみなりの国に招待してくれました。未来都市のようなかみなりの国の楽しさも抜群の「だるまちゃん」シリーズ第２作。', '家出少年のホーティがもぐりこんだのは、普通でない人間たちが集うカーニヴァル。団長のモネートルには奇妙な趣味があった。宇宙から来た不思議な水晶の蒐集と研究だ。水晶たちが夢をみるとき、人や動物や植物が生まれる―モネートルはそれを利用して、己の野望を果たそうとしていたのだ。そのことを知ったホーティやカーニヴァルの団員は、恐ろしい運命の渦に巻きこまれていく。幻想sfの巨匠がつむぎだす珠玉の名品。', '信濃国立石領多岐家では当主が病に倒れ、当主に子がないため甥御を跡を継がせることになっていた。だが、実はお手つきになった女中の静が、秘かに嫡子を生んでいるということを筆頭家老の武部が明かす。その静は、かつてこの藩で剣術指南をしていた男と共に山里に在り…。', '私は他の女の子たちよりも早く老けるだろう。チャイルドモデルから芸能界へ―幼い頃からtvの中で生きてきた美しくすこやかな少女・夕子。ある出来事をきっかけに、彼女はブレイクするが…少女の心とからだに流れる18年の時間を描く。芥川賞受賞第一作。', 'peeters 1992'}

In [ ]:
# Replace empty strings of description with NaN
books_data.Description = books_data.Description.replace(r'^\s*$', np.nan, regex=True)

books_data[books_data.length.isin(range(1,min_description_word_count+1))][["Id", "Name", "Description", "length"]]\
.sort_values(by=["length"], ascending=True).head(5)

,Id,Name,Description,length
97133,3268135,teaching in multilingual classrooms: a teacher...,textformat02gt,1
71302,3192324,最悪 [saiaku],前途一片黑暗，沒有出口。這樣的人生該持續下去嗎？在經濟蕭條壓力下苦求生存的鐵工廠老闆川谷，同...,1
14523,3035896,人行道的尽头 [rénxíngdào de jìntóu],《人行道的尽头》谢尔·希尔弗斯坦作品集06是作者的第一本诗集绘本，1974年一经出版便立刻被...,1
67526,3181604,号泣する準備はできていた [gōkyūsuru junbi wa dekite ita],私はたぶん泣きだすべきだったのだ。身も心もみちたりていた恋が終わり、淋しさのあまりねじ切れて...,1
96622,3266695,狼と香辛料 iv,ホロの故郷・ヨイツを目指し、二人の旅は続く……。狼神ホロの故郷・ヨイツを探すため、北を目指す...,1

In [ ]:
books_data.dropna(subset=["Description"], inplace=True)

# Drop records with very short description
books_data.drop(books_data.index[books_data.length.isin(range(0,min_description_word_count+1))], inplace = True)
del books_data["length"]

In [ ]:
# Convert unknown to NaN
books_data["Publisher"] = books_data.Publisher.replace('unknown',np.nan)
books_data = books_data.sort_values(by="Publisher", na_position='last')\
.drop_duplicates(subset=["Name", "Authors", "Description"], keep='first')

### Extract and Remove Book Series Information from the Book Name

In [ ]:
series_pattern =  "(?:[;]\s*|\(\s*)([^\(;]*\s*#\s*\d+(?:\.?\d+|\\&\d+|-?\d*))"
def get_book_series_info(text):
    series_info = re.findall(series_pattern, text)
    if series_info:
        series_info = " ".join([i.replace(" ", "_") for i in series_info])
        return series_info
    else:
        return np.nan

books_data['BookSeriesInfo'] = books_data.Name.apply(get_book_series_info)

In [ ]:
series_remove_pattern = r"(?:[\(]\s*[^\(;]*\s*#\s*\d+(?:\.?\d+|\\&\d+|-?\d*)(?:;|\))|\s*[^\(;]*\s*#\s*\d+(?:\.?\d+|\\&\d+|-?\d*)\))"
def remove_series_info(text):
    return re.sub(series_remove_pattern, r'', text)

books_data["Title"]= books_data["Name"].str.replace(series_remove_pattern, r'',regex=False).str.strip()

###  Impute Missing Language Information Using the Language of the Book Name

In [ ]:
tc = TextCat()

def detect_language(text):
    # Check if text is valid and not a missing value
    if isinstance(text, str) and text:
        text = " ".join(text.split()[:5])
        if text.isnumeric():
            return 'eng'
        else:
            return tc.guess_language(text).strip()
    # Handle missing values by returning a default or placeholder
    else:
        return 'unknown'  # Or any other suitable placeholder

In [ ]:
ddf = dd.from_pandas(books_data, npartitions=4*multiprocessing.cpu_count())
books_data["Language"] = ddf.map_partitions(
    lambda df: df.apply(lambda x: detect_language(x['Name']), axis=1),
    meta={'Language': 'object'}  # Specify meta for "Language" column
).compute()

AttributeError: 'DataFrame' object has no attribute 'name'

In [ ]:
"""
 Takes longer time to process thousands records hence results are presaved in preprocessed.csv
 """
"""ddf = dd.from_pandas(books_data, npartitions=4*multiprocessing.cpu_count())
books_data["Language"] = ddf.map_partitions(lambda df: df.apply(lambda x: detect_language(x['Name']) if pd.isna(x['Language']) else x['Language'], axis=1)).compute()
books_data.isna().sum()
"""

'ddf = dd.from_pandas(books_data, npartitions=4*multiprocessing.cpu_count())\nbooks_data["Language"] = ddf.map_partitions(lambda df: df.apply(lambda x: detect_language(x[\'Name\']) if pd.isna(x[\'Language\']) else x[\'Language\'], axis=1)).compute()\nbooks_data.isna().sum()\n'

In [ ]:
temp_preview = books_data.head(5).copy()
ddf = dd.from_pandas(temp_preview, npartitions=4*multiprocessing.cpu_count())
temp_preview["Language"] = ddf.map_partitions(lambda df: df.apply(lambda x: detect_language(x['Name']) if pd.isna(x['Language']) else x['Language'], axis=1)).compute()
temp_preview

,Id,Name,Authors,ISBN,PublishYear,Publisher,Language,Description,BookSeriesInfo,Title
14688,3036342,dodge the devil (gunsmoke #5),joseph a. west,0451219724,2006,"""signet""",eng,bareknuckle prizefighter ben hillman beats dod...,gunsmoke_#5,dodge the devil (gunsmoke #5)
129264,3366064,the picture life of edward heath,iain sproat,0851664326,1971,(18 grosvenor st. w.1),eng,a brief biography of the english conservative ...,NaN,the picture life of edward heath
114134,3319721,lettres de chine,victor segalen,2264018690,1993,10-18,fre,net als slauerhoff was de fransman victor sega...,NaN,lettres de chine
141168,3402213,l'âge difficile,henry james,2264024542,1998,10-18,fre,this work has been selected by scholars as bei...,NaN,l'âge difficile
254812,3719982,dans la deche a paris et a londres,george orwell,2264030399,2001,10-18,fur,a memoir of the authors time among the despera...,NaN,dans la deche a paris et a londres

## Remove Double Quotes from Publisher Name.

In [ ]:
books_data["Publisher"] = books_data["Publisher"].str.replace('"','')

## Transform Book and Author Names into Single Token

In [ ]:
books_data["Authors"] = books_data["Authors"].str.strip().str.replace(' ','_')
books_data["Publisher"] = books_data["Publisher"].str.strip().str.replace(' ','_')
books_data.head(5)

,Id,Name,Authors,ISBN,PublishYear,Publisher,Language,Description,BookSeriesInfo,Title
14688,3036342,dodge the devil (gunsmoke #5),joseph_a._west,0451219724,2006,signet,NaN,bareknuckle prizefighter ben hillman beats dod...,gunsmoke_#5,dodge the devil (gunsmoke #5)
129264,3366064,the picture life of edward heath,iain_sproat,0851664326,1971,(18_grosvenor_st._w.1),NaN,a brief biography of the english conservative ...,NaN,the picture life of edward heath
114134,3319721,lettres de chine,victor_segalen,2264018690,1993,10-18,fre,net als slauerhoff was de fransman victor sega...,NaN,lettres de chine
141168,3402213,l'âge difficile,henry_james,2264024542,1998,10-18,fre,this work has been selected by scholars as bei...,NaN,l'âge difficile
254812,3719982,dans la deche a paris et a londres,george_orwell,2264030399,2001,10-18,NaN,a memoir of the authors time among the despera...,NaN,dans la deche a paris et a londres

###  Merge All the Textual Summary into a Single Summary Column.

In [ ]:
books_data["bow"] = books_data[["BookSeriesInfo", 'Authors', 'Publisher', 'Language']].fillna('').agg(' '.join, axis=1)

In [ ]:
books_data.bow.iloc[8375]

' lawrence_durrell buchet_chastel '

In [ ]:
# Save cleaned data
books_data.to_csv("C://Users/personal/Downloads/goodreadbooks/preprocessed.csv", sep=",", index=False)

#  Feature Engineering

In [ ]:
# Fetch preprocessed cleaned data
fe_data = pd.read_csv("C://Users/personal/Downloads/goodreadbooks/preprocessed.csv", usecols=["Id", "Name", "Language", "Description", "bow"])
fe_data.head()

,Id,Name,Language,Description,bow
0,3036342,dodge the devil (gunsmoke #5),NaN,bareknuckle prizefighter ben hillman beats dod...,gunsmoke_#5 joseph_a._west signet
1,3366064,the picture life of edward heath,NaN,a brief biography of the english conservative ...,iain_sproat (18_grosvenor_st._w.1)
2,3319721,lettres de chine,fre,net als slauerhoff was de fransman victor sega...,victor_segalen 10-18 fre
3,3402213,l'âge difficile,fre,this work has been selected by scholars as bei...,henry_james 10-18 fre
4,3719982,dans la deche a paris et a londres,NaN,a memoir of the authors time among the despera...,george_orwell 10-18

In [ ]:
kw_model = KeyBERT(model='distilbert-base-nli-mean-tokens')

In [ ]:
batch_size = 1000  # Adjust as needed
for i in range(0, len(fe_data), batch_size):
    batch = fe_data[i:i + batch_size]
    batch["keywords"] = batch.Description.apply(get_keywords)
    # ... (Store or process the batch results)

<ipython-input-109-d770cccd870f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch["keywords"] = batch.Description.apply(get_keywords)
<ipython-input-109-d770cccd870f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch["keywords"] = batch.Description.apply(get_keywords)
<ipython-input-109-d770cccd870f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch["keywords"] = batch.Description.apply(get_keywords)
<ipython-input-109-d770cccd870f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch["keywords"] = batch.Description.apply(get_keywords)
<ipython-input-109-d770cccd870f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch["keywords"] = batch.Description.apply(get_keywords)
<ipython-input-109-d770cccd870f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch["keywords"] = batch.Description.apply(get_keywords)
<ipython-input-109-d770cccd870f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch["keywords"] = batch.Description.apply(get_keywords)
<ipython-input-109-d770cccd870f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batch["keywords"] = batch.Description.apply(get_keywords)

In [ ]:
import multiprocessing

# ... (Your existing code)

with multiprocessing.Pool(processes=multiprocessing.cpu_count()) as pool:
    fe_data["keywords"] = pool.map(get_keywords, fe_data.Description)

In [ ]:
kw_model = KeyBERT(stop_words='english')  # Or use a custom list

## Keyword Extraction Using KeyBERT
#### Use keyBERT to extract relevant keywords from the Description. It is developed and maintained by Maarten Grootendorst. As stated in its document KeyBERT uses BERT-embeddings and cosine similarity to find the sub-phrases in a document that are the most similar to the document itself.

In [ ]:
#kw_model = KeyBERT()

def get_keywords(text):
    keywords = kw_model.extract_keywords(text, keyphrase_ngram_range=(1, 1), stop_words="english")
    keywords = " ".join([k[0] for k in keywords])
    return keywords

fe_data["keywords"] = fe_data.Description.apply(get_keywords)

In [ ]:
fe_data.keywords.head()

In [ ]:
fe_data["keywords"] = fe_data[['bow', 'keywords']].fillna('').agg(' '.join, axis=1)
fe_data.drop(['bow', 'Description'], axis = 1, inplace=True)

###  Remove duplicated Book Names

In [ ]:
fe_data = fe_data.drop_duplicates(subset=["Name"], keep='first')

In [ ]:
# Store results
fe_data.to_csv("C://Users/personal/Downloads/goodreadbooks/keywords.csv", sep=",", index=False)

# Text Representation

In [ ]:
# Fetch keywords data
model_data = pd.read_csv("C://Users/personal/Downloads/goodreadbooks/keywords.csv")
model_data.head()

# Vectorize the Keywords Summary Using TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(analyzer = 'word',
                        min_df=3,
                        max_df = 0.6,
                        stop_words="english",
                        encoding = 'utf-8',
                        token_pattern=r"(?u)\S\S+")
tfidf_encoding = tfidf.fit_transform(model_data["keywords"])

In [ ]:
# Preview first 100 words in the vocabulary
print(tfidf.get_feature_names_out()[1:100])

### Visualize the TF-IDF word embeddings

In [ ]:
tfidf_df = pd.DataFrame(tfidf_encoding.toarray(), index=model_data["Name"], columns=tfidf.get_feature_names_out())

# Find top 50 books with maximum tf-idf total score
tfidf_df["total"]= tfidf_df.sum(axis=1)
tfidf_df = tfidf_df.sort_values("total", ascending=False)
del tfidf_df["total"]

In [ ]:
# Leave first few words containing years and select top 50 books
tfidf_df_preview = tfidf_df.iloc[100:150,25:].copy()
tfidf_df_preview = tfidf_df_preview.stack().reset_index()
tfidf_df_preview = tfidf_df_preview.rename(columns={0:'tfidf', 'Name': 'book','level_1': 'term'})
tfidf_df_preview = tfidf_df_preview.sort_values(by=['book','tfidf'], ascending=[True,False]).groupby(['book']).head(10)
display(tfidf_df_preview)

In [ ]:
def process_word_matrix(word_vec):
    # Remove underscores in terms
    word_vec.term = word_vec.term.str.replace('_',' ')

    # Remove terms with zero tfidf score
    word_vec = word_vec[word_vec.tfidf > 0]

    return word_vec

tfidf_vec = process_word_matrix(tfidf_df_preview.copy())
tfidf_vec.iloc[0:5]

In [ ]:
import altair as alt
grid = alt.Chart(tfidf_vec).encode(
    x = 'rank:O',
    y = 'book:N'
).transform_window(
    rank = "dense_rank()",
    sort = [alt.SortField("tfidf", order="descending")],
    groupby = ["book"],
)
heatmap = grid.mark_rect(size=5).encode(
    alt.Color('tfidf:Q', scale=alt.Scale(scheme='redpurple'))
)
text = grid.mark_text(align='center', baseline='middle', lineBreak='').encode(
    text = 'term:N',
    color = alt.condition(alt.datum.tfidf >= 0.23, alt.value('white'), alt.value('black'))
)
(heatmap+text).properties(width = 800)

# Cosine Similarity Between Books Vector Representation

######

Once the numerical vector representation of the data is created for each book, it becomes possible to apply all the techniques applicable in a geometric space. It is possible to find similarity between two vectors (and thereby between books represented as vectors).

In [ ]:
book_cosine_sim = cosine_similarity(tfidf_encoding, tfidf_encoding)

In [ ]:

# Preview Similarity Matrix
book_cosine_sim

In [ ]:
# Vidualize similarity between books
plt.figure(figsize=(6, 6), dpi=80)
plt.spy(book_cosine_sim, precision = 0.1, markersize = 0.04)
plt.tight_layout()
plt.show()

# Recommendation
Purpose is: given a book name, find top n similar books based on cosine similarity score. In real use cases, the input book could be the book a user has read, has rated highly or have added to the read later list. Books are recommended utilising the following information through keywords:

In [ ]:
books = pd.Series(model_data['Name'])

def recommend_books_similar_to(book_name, n=5, cosine_sim_mat=book_cosine_sim):
    # get index of the imput book
    input_idx = books[books == book_name].index[0]
    # Find top n similar books with decreasing order of similarity score
    top_n_books_idx = list(pd.Series(cosine_sim_mat[input_idx]).sort_values(ascending = False).iloc[1:n+1].index)
    # [1:6] to exclude 0 (index 0 is the input movie itself)

    books_list = list(books)
    recommended_books = [books[i] for i in top_n_books_idx]

    return recommended_books

# 1. Series Information
Suggest other books from the similar series.
In the example, series information images of america is used to recommend books relating to different parts of America from the same series (new jersey).

In [ ]:
# Recommendations with series information
print("\033[1m{}\033[0m".format("Recommendation (Series Information) based on the read: The Eastland Disaster (Images of America: Illinois)"))
display(recommend_books_similar_to("the eastland disaster (images of america: illinois)", 5))

# 2. Other Books In Numbered Series
Suggest other books in the sequence from the same series.
In the example below, other books in the series sequence of Antique Lover are recommended.

In [ ]:
# Recommendations with series information numbered
print("\n\033[1m{}\033[0m".format("Recommendation (Numbered Series) based on the read: The Majolica Murders (Antique Lover, #5)"))
display(recommend_books_similar_to("the majolica murders (antique lover, #5)", 5))

# 3.Theme
Utilise keywords depicting semantic meaning of the theme of the book to suggest books from similar themes.
In the example below, all the books about developing programming skills irrespective of programming language are recommended.

In [ ]:
print("\n\033[1m{}\033[0m".format("Recommendation (Theme: Programming) based on the read: The Practice of Programming (Addison-Wesley Professional Computing Series)"))
display(recommend_books_similar_to('the practice of programming (addison-wesley professional computing series)', 5))

# 4. Author
Suggest other works of the same Author.

In [ ]:
print("\n\033[1m{}\033[0m".format("Recommendation (Author: Dean Koontz) based on the read: Cold Fire"))
display(recommend_books_similar_to("cold fire",5))